apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: pgAdmin4 - Web Application for Managing Postgres Database
    runtime: python3
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    antinex: pgadmin
    purpose: database-management
    layer: database
  name: pgadmin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        antinext: pgadmin
    spec:
      containers:
      - env:
        - name: DEFAULT_SERVER_HOST
          value: 0.0.0.0
        - name: DEFAULT_SERVER_PORT
          value: "5050"
        - name: PGADMIN_SETUP_EMAIL
          value: admin@email.com
        - name: PGADMIN_SETUP_PASSWORD
          value: postgres
        - name: POSTGRES_HOSTNAME
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: SERVER_MODE
          value: "True"
        image: jayjohnson/pgadmin4:1.0.0
        name: pgadmin
        ports:
        - containerPort: 5050
        resources: {}
      hostname: pgadmin
      restartPolicy: Always
status: {}
