apiVersion: v1
kind: Service
metadata:
  annotations:
    description: pgAdmin4 - Web Application for Managing Postgres Database
    runtime: python3
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    antinex: pgadmin
    purpose: database-management
    layer: database
  name: pgadmin
spec:
  ports:
  - name: "83"
    port: 83
    targetPort: 5050
  selector:
    antinex: pgadmin
status:
  loadBalancer: {}
