apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: Jupyter - Web Application for IPython Notebooks Data Science and Analysis
    runtime: python3
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    antinex: jupyter
    purpose: analysis
    layer: web
    users: data-scientists
    auth: basic
    messaging: redis
    cache: redis
    pubsub: publisher
  name: jupyter
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        antinex: jupyter
        purpose: analysis
        layer: web
        users: data-scientists
        auth: basic
        messaging: redis
        cache: redis
        pubsub: publisher
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - cd /opt/antinex/core/docker/jupyter && export HOME=/opt/antinex/core/docker/jupyter && . /opt/venv/bin/activate && source /opt/antinex/api/envs/openshift-dev.env && env | sort && /opt/antinex/core/docker/jupyter/start-container.sh && tail -f /var/log/antinex/api/api.log
        env:
        - name: ANTINEX_URL
          value: http://api:8080
        - name: ANTINEX_USER
          value: root
        - name: ANTINEX_PASSWORD
          value: "123321"
        - name: BROKER_URL
          value: redis://redis:6379/6
        - name: JUPYTER_PORT
          value: "8888"
        - name: JUPYTER_PASS
          value: admin
        - name: SHARED_DIR
          value: /opt/data
        - name: DEPLOY_CONFIG
          value: log_to_splunk
        - name: LOG_NAME
          value: jupyter
        - name: ENV_NAME
          value: ocp
        - name: SHARED_LOG_CFG
          value: /opt/spylunking/spylunking/log/shared-logging.json
        - name: LOG_HANDLER_NAME
          value: console
        - name: SPLUNK_HANDLER_NAME
          value: splunk
        - name: SPLUNK_INDEX
          value: antinex
        - name: SPLUNK_ADDRESS
          value: "192.168.0.21:8088"
        - name: SPLUNK_API_ADDRESS
          value: "192.168.0.21:8089"
        - name: SPLUNK_TCP_ADDRESS
          value: "192.168.0.21:1514"
        - name: SPLUNK_USER
          value: trex
        - name: SPLUNK_PASSWORD
          value: "123321"
        - name: SPLUNK_TOKEN
          value: 
        - name: SPLUNK_TOKEN
          value: 
        - name: SPLUNK_VERIFY
          value: "0"
        image: jayjohnson/antinex-jupyter:latest
        name: jupyter
        ports:
        - containerPort: 8888
        - containerPort: 8889
        - containerPort: 8890
        - containerPort: 6006
        resources: {}
      hostname: jupyter
      restartPolicy: Always
status: {}
