apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: AntiNex API Consumers - Celery Django Rest Framework Backend Worker
    runtime: python3
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    antinex: worker
    purpose: worker
    layer: backend
    messaging: redis
    cache: redis
    pubsub: consumer
  name: worker
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        antinex: worker
        purpose: worker
        layer: backend
        messaging: redis
        cache: redis
        pubsub: consumer
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - cd /opt/antinex-api && . /opt/venv/bin/activate && source /opt/antinex-api/envs/openshift-no-hostnames.env && env | sort && /opt/antinex-api/run-worker.sh && tail -f /etc/hosts
        env:
        - name: ANTINEX_AUTH_URL
          value: redis://redis:6379/6
        - name: ANTINEX_RESULT_AUTH_URL
          value: redis://redis:6379/9
        - name: ANTINEX_CA_CERTS
        - name: ANTINEX_CERTFILE
        - name: ANTINEX_DELIVERY_MODE
          value: persistent
        - name: ANTINEX_EXCHANGE_NAME
          value: webapp.predict.requests
        - name: ANTINEX_EXCHANGE_TYPE
          value: topic
        - name: ANTINEX_KEYFILE
        - name: ANTINEX_QUEUE_NAME
          value: webapp.predict.requests
        - name: ANTINEX_TLS_PROTOCOL
        - name: ANTINEX_WORKER_ENABLED
          value: "1"
        - name: ANTINEX_WORKER_ONLY
          value: "0"
        - name: ANTINEX_WORKER_SSL_ENABLED
          value: "0"
        - name: CACHEOPS_ENABLED
          value: "1"
        - name: CELERY_ENABLED
          value: "1"
        - name: COLLECT_STATICS
          value: "1"
        - name: DJANGO_ALLOWED_HOSTS
          value: '*'
        - name: DJANGO_CONFIGURATION
          value: Development
        - name: DJANGO_DEBUG
          value: "yes"
        - name: DJANGO_SECRET_KEY
          value: supersecret
        - name: DJANGO_TEMPLATE_DEBUG
          value: "yes"
        - name: ENVIRONMENT
          value: Development
        - name: NUM_WORKERS
          value: "4"
        - name: POSTGRES_DB
          value: webapp
        - name: POSTGRES_HOST
          value: primary
        - name: POSTGRES_PASSWORD
          value: antinex
        - name: POSTGRES_USER
          value: antinex
        - name: POSTGRES_PORT
          value: "5432"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: USE_ENV
          value: openshift-no-hostnames
        - name: USE_VENV
          value: /opt/venv
        - name: WEBAPP_HOST
          value: api
        - name: WEBAPP_PORT
          value: "8080"
        image: jayjohnson/ai-core:latest
        resources:
          requests:
            cpu: 2000m
            memory: 1000m
          requests:
            cpu: 2000m
            memory: 1000m
        name: worker
      hostname: worker
      restartPolicy: Always
status: {}
