apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: AntiNex - AI Core - Celery Worker for Training and Making Predictions
    runtime: python3
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    antinex: core
    purpose: worker
    layer: backend
    ai.framework: keras
    ai.backend: tensorflow
    layer: backend
  name: core
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        antinex: core
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - cd /opt/antinex-core && . /opt/venv/bin/activate && source /opt/antinex-api/envs/openshift-dev.env && env | sort && /opt/antinex-core/run-antinex-core.sh
        env:
        - name: BROKER_URL
          value: redis://redis:6379/6
        - name: USE_ENV
          value: openshift-dev
        - name: SHARED_DIR
          value: /opt/data
        image: jayjohnson/ai-core:latest
        name: core
        resources: {}
      hostname: core
      restartPolicy: Always
status: {}
