apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    description: AntiNex Network Pipeline Consumer - Processing Network Published Packets
    runtime: python3
    kompose.cmd: kompose convert -f compose.yml
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    antinex: pipeline
    purpose: network-traffic-packet-consumer
    layer: backend
    messaging: redis
    cache: redis
    pubsub: consumer
  name: pipeline
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        antinex: pipeline
        purpose: network-traffic-packet-consumer
        layer: backend
        messaging: redis
        cache: redis
        pubsub: consumer
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - cd /opt/antinex/pipeline && . /opt/venv/bin/activate && source /opt/antinex/api/envs/openshift-dev.env && env | sort && /opt/antinex/pipeline/network_pipeline/scripts/packets_redis.py
        env:
        - name: ANTINEX_BATCH_SIZE
          value: "32"
        - name: ANTINEX_CLIENT_DEBUG
          value: "0"
        - name: ANTINEX_CLIENT_VERBOSE
          value: "1"
        - name: ANTINEX_CONVERT_DATA
          value: "1"
        - name: ANTINEX_CONVERT_DATA_TYPE
          value: float
        - name: ANTINEX_EMAIL
          value: "123321"
        - name: ANTINEX_EPOCHS
          value: "15"
        - name: ANTINEX_FEATURES_TO_PROCESS
          value: idx,arp_hwlen,arp_hwtype,arp_id,arp_op,arp_plen,arp_ptype,dns_default_aa,dns_default_ad,dns_default_an,dns_default_ancount,dns_default_ar,dns_default_arcount,dns_default_cd,dns_default_id,dns_default_length,dns_default_ns,dns_default_nscount,dns_default_opcode,dns_default_qd,dns_default_qdcount,dns_default_qr,dns_default_ra,dns_default_rcode,dns_default_rd,dns_default_tc,dns_default_z,dns_id,eth_id,eth_type,icmp_addr_mask,icmp_code,icmp_gw,icmp_id,icmp_ptr,icmp_seq,icmp_ts_ori,icmp_ts_rx,icmp_ts_tx,icmp_type,icmp_unused,ip_id,ip_ihl,ip_len,ip_tos,ip_version,ipv6_fl,ipv6_hlim,ipv6_nh,ipv6_plen,ipv6_tc,ipv6_version,ipvsix_id,pad_id,tcp_dport,tcp_fields_options.MSS,tcp_fields_options.NOP,tcp_fields_options.SAckOK,tcp_fields_options.Timestamp,tcp_fields_options.WScale,tcp_id,tcp_seq,tcp_sport,udp_dport,udp_id,udp_len,udp_sport
        - name: ANTINEX_HISTORIES
          value: val_loss,val_acc,loss,acc
        - name: ANTINEX_IGNORE_FEATURES
        - name: ANTINEX_INCLUDE_FAILED_CONVERSIONS
          value: "false"
        - name: ANTINEX_LOSS
          value: binary_crossentropy
        - name: ANTINEX_METRICS
          value: accuracy
        - name: ANTINEX_MISSING_VALUE
          value: "-1.0"
        - name: ANTINEX_ML_TYPE
          value: classification
        - name: ANTINEX_NUM_SPLITS
          value: "2"
        - name: ANTINEX_OPTIMIZER
          value: adam
        - name: ANTINEX_PASSWORD
          value: "123321"
        - name: ANTINEX_PREDICT_FEATURE
          value: label_value
        - name: ANTINEX_PUBLISH_ENABLED
          value: "1"
        - name: ANTINEX_PUBLISH_REQUEST_FILE
          value: /opt/antinex/client/examples/predict-rows-scaler-full-django.json
        - name: ANTINEX_PUBLISH_TO_CORE
          value: "1"
        - name: ANTINEX_SEED
          value: "42"
        - name: ANTINEX_SORT_VALUES
        - name: ANTINEX_TEST_SIZE
          value: "0.2"
        - name: ANTINEX_URL
          value: http://api:8010
        - name: FORWARD_BROKER_URL
          value: redis://redis:6379/0
        - name: ANTINEX_USER
          value: root
        - name: ANTINEX_USE_MODEL_NAME
          value: Full-Django-AntiNex-Simple-Scaler-DNN
        - name: ANTINEX_VERSION
          value: "1"
        - name: USE_VENV
          value: /opt/venv
        - name: DEPLOY_CONFIG
          value: log_to_splunk
        - name: LOG_NAME
          value: pipeline
        - name: ENV_NAME
          value: ocp
        - name: SHARED_LOG_CFG
          value: /opt/spylunking/spylunking/log/shared-logging.json
        - name: LOG_HANDLER_NAME
          value: console
        - name: SPLUNK_HANDLER_NAME
          value: splunk
        - name: SPLUNK_INDEX
          value: antinex
        - name: SPLUNK_ADDRESS
          value: "192.168.0.21:8088"
        - name: SPLUNK_API_ADDRESS
          value: "192.168.0.21:8089"
        - name: SPLUNK_TCP_ADDRESS
          value: "192.168.0.21:1514"
        - name: SPLUNK_USER
          value: trex
        - name: SPLUNK_PASSWORD
          value: "123321"
        - name: SPLUNK_TOKEN
          value: 
        - name: SPLUNK_VERIFY
          value: "0"
        image: jayjohnson/antinex-pipeline:latest
        name: pipeline
        resources: {}
      hostname: pipeline
      restartPolicy: Always
status: {}
