apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2018-05-27T20:06:05Z
  name: redis-antinex-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10G
  nfs:
    path: /exports/redis-antinex
    server: localhost
  persistentVolumeReclaimPolicy: Retain
