apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "redis-antinex-pvc"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "10G"
  volumeName: "redis-antinex-pv"
